project:
  type: website

website:
  title: "n0dn | The linked data"
  navbar:
    left:
      - href: index.qmd
        text: "ğŸ  Home"
      - about.qmd
      - href: descargables.qmd
      
  page-footer:
    left: "Â© 2025 n0dn | The linked Data. Todos los derechos reservados."
    right:
      - icon: twitter
        href: https://x.com/n0dn_
      - icon: linkedin
        href: https://www.linkedin.com/in/norberto-bustos/
      - text: "n0dn.info@proton.me"
        href: "mailto:n0dn.info@proton.me"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    dark_mode: true

editor: visual