project:
  type: website

website:
  title: "n0dn | The linked data"
  # Men칰 de navegaci칩n
  navbar:
    left:
      - href: index.qmd
        text: "游 Inicio" # Cambio "Home" por "Inicio" para consistencia en espa침ol
      - about.qmd
      - href: descargables.qmd
        text: "Descargables" # A침adido texto visible para el enlace descargables.qmd
      
  # Pie de p치gina
  page-footer:
    left: "춸 2025 n0dn | The linked Data. Todos los derechos reservados."
    right:
      - icon: twitter
        href: https://x.com/n0dn_
      - icon: linkedin
        href: https://www.linkedin.com/in/norberto-bustos/
      - text: "n0dn.info@proton.me"
        href: "mailto:n0dn.info@proton.me"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true # Tabla de contenidos
    dark_mode: true # Soporte para modo oscuro

editor: visual